config/routes.rb
Rails.application.routes.draw do
  resources :families
  resources :properties
  resources :birds

end

app/models/bird.rb
class Bird
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :family, type: String
  field :continents, type: String
  field :visible, type: Mongoid::Boolean, default: false
  field :uniqueitem, type: Boolean

  validates :name, :continents, :visible, presence: true

  has_many :properties
  has_many :families
end

app/models/family.rb
class Family
  include Mongoid::Document
  field :family_name, type: String
  field :description, type: String

  belongs_to :bird
end

app/models/property.rb
class Property
  include Mongoid::Document
  field :name, type: String
  field :description, type: String

  belongs_to :bird
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/birds_controller.rb
class BirdsController < ApplicationController
  before_action :set_bird, only: [:show, :edit, :update, :destroy]

  OK = 200
  CREATED = 201
  NO_CONTENT = 204
  NOT_FOUND = 404
  BAD_REQUEST = 400
  INTERNAL_SERVER_ERROR = 500

  # GET /birds
  # GET /birds.json
  def index
    @birds = Bird.all.to_a
    begin
      respond_to do |format|
        format.json { render json: {items: @birds, description: "List all visible birds in the registry", additionalProperties: false, title: "POST /birds [request]",:status => OK } }
      end
    rescue => e
      render json: ({:status => INTERNAL_SERVER_ERROR})
    end
  end

  # GET /birds/1
  # GET /birds/1.json
  def show
    if @bird
      respond_to do |format|
        format.json { render json: {required: @bird, properties: @bird.properties, families: @bird.families, title: "POST /birds [request]", description: "Get bird by id",:status => OK }}
      end
    else
      respond_to do |format|
        format.json { render json: {:status => NOT_FOUND} }
      end
    end
  end

  # GET /birds/new
  def new
    @bird = Bird.new

    respond_to do |format|
      format.json { render json: @bird }
    end
  end

  # GET /birds/1/edit
  def edit
  end

  # POST /birds
  # POST /birds.json
  def create
    begin
    respond_to do |format|
      if @bird.save(bird_params)
        format.json { render json: {items: @birds, properties: @bird.properties, families: @bird.families, description: "Add a new bird to the library",:status => CREATED} }
      else
        format.json { render json: @bird.errors, :status => NOT_FOUND }
      end
    end
    else
        render json:({:status => INTERNAL_SERVER_ERROR})
    end
  end

  # PATCH/PUT /birds/1
  # PATCH/PUT /birds/1.json
  def update
    respond_to do |format|
      if @bird.update(bird_params)
        format.html { redirect_to @bird, notice: 'Bird was successfully updated.' }
        format.json { render :show, status: :ok, location: @bird }
      else
        format.html { render :edit }
        format.json { render json: @bird.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /birds/1
  # DELETE /birds/1.json
  def destroy
    @bird.destroy
        
    begin
      respond_to do |format|
        format.json { render json:({:status => NO_CONTENT}) }
      end
    else
      render json: ({:status => INTERNAL_SERVER_ERROR})
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bird
      @bird = Bird.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bird_params
      params.require(:bird).permit(:name, :family, :continents, :visible, :uniqueitem)
    end
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_action :set_family, only: [:show, :edit, :update, :destroy]

  # GET /families
  # GET /families.json
  def index
    @families = Family.all
  end

  # GET /families/1
  # GET /families/1.json
  def show
  end

  # GET /families/new
  def new
    @family = Family.new
  end

  # GET /families/1/edit
  def edit
  end

  # POST /families
  # POST /families.json
  def create
    @family = Family.new(family_params)

    respond_to do |format|
      if @family.save
        format.html { redirect_to @family, notice: 'Family was successfully created.' }
        format.json { render :show, status: :created, location: @family }
      else
        format.html { render :new }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /families/1
  # PATCH/PUT /families/1.json
  def update
    respond_to do |format|
      if @family.update(family_params)
        format.html { redirect_to @family, notice: 'Family was successfully updated.' }
        format.json { render :show, status: :ok, location: @family }
      else
        format.html { render :edit }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /families/1
  # DELETE /families/1.json
  def destroy
    @family.destroy
    respond_to do |format|
      format.html { redirect_to families_url, notice: 'Family was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family
      @family = Family.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def family_params
      params.require(:family).permit(:family_name, :description)
    end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/birds_helper.rb
module BirdsHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/birds/_form.html.erb
<%= form_for(@bird) do |f| %>
  <% if @bird.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bird.errors.count, "error") %> prohibited this bird from being saved:</h2>

      <ul>
      <% @bird.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :family %><br>
    <%= f.text_field :family %>
  </div>
  <div class="field">
    <%= f.label :continents %><br>
    <%= f.text_field :continents %>
  </div>
  <div class="field">
    <%= f.label :visible %><br>
    <%= f.check_box :visible %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/birds/edit.html.erb
<h1>Editing Bird</h1>

<%= render 'form' %>

<%= link_to 'Show', @bird %> |
<%= link_to 'Back', birds_path %>

app/views/birds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Birds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Family</th>
      <th>Continents</th>
      <th>Visible</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @birds.each do |bird| %>
      <tr>
        <td><%= bird.name %></td>
        <td><%= bird.family %></td>
        <td><%= bird.continents %></td>
        <td><%= bird.visible %></td>
        <td><%= link_to 'Show', bird %></td>
        <td><%= link_to 'Edit', edit_bird_path(bird) %></td>
        <td><%= link_to 'Destroy', bird, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bird', new_bird_path %>

app/views/birds/new.html.erb
<h1>New Bird</h1>

<%= render 'form' %>

<%= link_to 'Back', birds_path %>

app/views/birds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bird.name %>
</p>

<p>
  <strong>Family:</strong>
  <%= @bird.family %>
</p>

<p>
  <strong>Continents:</strong>
  <%= @bird.continents %>
</p>

<p>
  <strong>Visible:</strong>
  <%= @bird.visible %>
</p>

<%= link_to 'Edit', edit_bird_path(@bird) %> |
<%= link_to 'Back', birds_path %>

app/views/families/_form.html.erb
<%= form_for(@family) do |f| %>
  <% if @family.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@family.errors.count, "error") %> prohibited this family from being saved:</h2>

      <ul>
      <% @family.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :family_name %><br>
    <%= f.text_field :family_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/families/edit.html.erb
<h1>Editing Family</h1>

<%= render 'form' %>

<%= link_to 'Show', @family %> |
<%= link_to 'Back', families_path %>

app/views/families/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Families</h1>

<table>
  <thead>
    <tr>
      <th>Family name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @families.each do |family| %>
      <tr>
        <td><%= family.family_name %></td>
        <td><%= family.description %></td>
        <td><%= link_to 'Show', family %></td>
        <td><%= link_to 'Edit', edit_family_path(family) %></td>
        <td><%= link_to 'Destroy', family, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Family', new_family_path %>

app/views/families/new.html.erb
<h1>New Family</h1>

<%= render 'form' %>

<%= link_to 'Back', families_path %>

app/views/families/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Family name:</strong>
  <%= @family.family_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @family.description %>
</p>

<%= link_to 'Edit', edit_family_path(@family) %> |
<%= link_to 'Back', families_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BirdLibrary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/properties/_form.html.erb
<%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form' %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Properties</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.name %></td>
        <td><%= property.description %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form' %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @property.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @property.description %>
</p>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>